/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Adivina extends javax.swing.JInternalFrame {

    /**
     * Creates new form Adivina
     */
    public Adivina() {
        initComponents();
        inicializarModelo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBienvenido = new javax.swing.JLabel();
        jLAdivina = new javax.swing.JLabel();
        jLInstroduceNumero = new javax.swing.JLabel();
        jTFNumeroIngresado = new javax.swing.JTextField();
        jLNumeroGenerado = new javax.swing.JLabel();
        jLMensajes = new javax.swing.JLabel();
        jLIntentos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMemoria = new javax.swing.JTable();

        jLBienvenido.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBienvenido.setText("¡Bienvenido al juego de Adivina el Número!");

        jLAdivina.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLAdivina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAdivina.setText("Adivina un número entre 1 y 1000");

        jLInstroduceNumero.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLInstroduceNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInstroduceNumero.setText("Introduce el numero aca!");

        jTFNumeroIngresado.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jTFNumeroIngresado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFNumeroIngresado.setText("0");
        jTFNumeroIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroIngresadoActionPerformed(evt);
            }
        });

        jLNumeroGenerado.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLNumeroGenerado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNumeroGenerado.setText("El numero secreto es: xxx");

        jLMensajes.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLMensajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMensajes.setText("Vacio");

        jLIntentos.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIntentos.setText("Intentos = 0");

        jTMemoria.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        jTMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTMemoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(jLAdivina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLMensajes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLInstroduceNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFNumeroIngresado)
                            .addComponent(jLIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jLNumeroGenerado, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAdivina)
                .addGap(30, 30, 30)
                .addComponent(jLNumeroGenerado)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLInstroduceNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jTFNumeroIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLIntentos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int numeroSecreto = ThreadLocalRandom.current().nextInt(1, 1001);
    private int intentos = 0;

    private void jTFNumeroIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroIngresadoActionPerformed
        try {
            // Leer el número ingresado y convertirlo a int
            int numeroIngresado = Integer.parseInt(jTFNumeroIngresado.getText());

            // Comparar el número ingresado con el número secreto
            if (numeroIngresado < numeroSecreto) {
                jLMensajes.setText("¡Más alto!");
                intentos++;
                jTFNumeroIngresado.setText("");
            } else if (numeroIngresado > numeroSecreto) {
                jLMensajes.setText("¡Más bajo!");
                intentos++;
                jTFNumeroIngresado.setText("");
            } else {
                jLMensajes.setText("¡Felicidades! Adivinaste el número.");
                jLNumeroGenerado.setText("Numero Encontado: " + numeroSecreto);
            }

            // Mostrar los intentos
            jLIntentos.setText("Intentos: " + intentos);
            
            
            modelo.addRow(new Object[]{numeroIngresado});

        } catch (NumberFormatException ex) {
            jLMensajes.setText("Por favor, ingresa un número válido.");
        }
    }//GEN-LAST:event_jTFNumeroIngresadoActionPerformed

    private void jTFNumeroIngresadoFocusLost(java.awt.event.FocusEvent evt) {
        jTFNumeroIngresado.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jTFNumeroIngresadoActionPerformed(e);
            }
        });

    }

    
    DefaultTableModel modelo = new DefaultTableModel();
    
    private void inicializarModelo() {
        modelo.addColumn("Memoria");
        jTMemoria.setModel(modelo);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAdivina;
    private javax.swing.JLabel jLBienvenido;
    private javax.swing.JLabel jLInstroduceNumero;
    private javax.swing.JLabel jLIntentos;
    private javax.swing.JLabel jLMensajes;
    private javax.swing.JLabel jLNumeroGenerado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNumeroIngresado;
    private javax.swing.JTable jTMemoria;
    // End of variables declaration//GEN-END:variables
}
